# Imagen base de Node.js
FROM node:18

# Crear el directorio de la aplicación
WORKDIR /usr/src/app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Construir la aplicación de React
RUN npm run build

# Usar una imagen ligera de NGINX para servir la aplicación
FROM nginx:alpine
COPY --from=0 /usr/src/app/build /usr/share/nginx/html

# Exponer el puerto donde correrá el frontend (80)
EXPOSE 80

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]