# Usa una imagen de Node.js más reciente
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de package.json e instala las dependencias
COPY package*.json ./
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto 3001 para el backend
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]